name: Run sports_clean

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: cd sports_clean && bun install

      - name: Run script
        env:
          DATABASE1_URL: ${{ secrets.DATABASE1_URL }}
        run: bun run sports_clean/main.js
